# Generated by Django 4.2.6 on 2023-11-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=50)),
                ('weather', models.CharField(max_length=59)),
                ('pressure', models.CharField(max_length=60)),
                ('kelvin_temperature', models.FloatField(max_length=60)),
                ('humidity', models.CharField(max_length=60)),
                ('celsius_temperature', models.FloatField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='city',
        ),
    ]
