# Generated by Django 4.2.6 on 2023-11-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0002_weather_delete_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='kelvin_temperature',
            field=models.FloatField(max_length=60, null=True),
        ),
    ]
