# Generated by Django 4.2.6 on 2023-11-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0003_alter_weather_kelvin_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='celsius_temperature',
            field=models.FloatField(max_length=60, null=True),
        ),
    ]
