# Generated by Django 4.2.6 on 2023-11-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0006_alter_weather_celsius_temperature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='celsius_temperature',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='weather',
            name='kelvin_temperature',
            field=models.CharField(default='', max_length=50),
        ),
    ]
